# Config file for automatic testing at travis-ci.org

language: javascript

node:
  - "6.9.1"

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install nodejs npm
  - sudo npm install n
  - n stable
  - npm install

script:
    - gulp test
