# Config file for automatic testing at travis-ci.org

language: javascript

node:
  - "6.9.1"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y nodejs npm
  - sudo npm install n
  - n stable

install:
  - npm install

script:
    - gulp test
